name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 uvicorn

      - name: Run API smoke tests
        run: |
          # Start FastAPI in background
          uvicorn src.api:app --host 127.0.0.1 --port 8000 &
          # Give the server time to start
          sleep 5
          # Smoke-test endpoints
          curl --fail http://127.0.0.1:8000/
          curl --fail http://127.0.0.1:8000/solve/classical
          curl --fail http://127.0.0.1:8000/solve/quantum
